
production:
  adapter: postgresql
  encoding: unicode
  database: hparks_production
  username: ubuntu
  password: ubuntu
  host: localhost
  port: 5432


development:
  adapter: postgresql
  encoding: unicode
  database: hparks_development
  username: ubuntu
  password: ubuntu
  host: localhost
  port: 5432
